import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { assertValidCityManifest } from './lib/city-manifest.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourceWeb = resolve(root, 'web');
const output = resolve(process.env.TRANSIT_DIST_DIR || resolve(root, 'dist'));
const require = createRequire(import.meta.url);
const cityId = String(process.env.TRANSIT_CITY || 'example').trim();
if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(cityId)) throw new Error('Invalid TRANSIT_CITY');

const cityPath = resolve(root, 'config/cities', `${cityId}.json`);
const city = JSON.parse(readFileSync(cityPath, 'utf8'));
assertValidCityManifest(city, cityId);

rmSync(output, { recursive: true, force: true });
mkdirSync(output, { recursive: true });
const excludedSourcePaths = new Set([
    resolve(sourceWeb, 'vendor'),
    resolve(sourceWeb, 'city-config.generated.js'),
]);
cpSync(sourceWeb, output, {
    recursive: true,
    filter: source => !excludedSourcePaths.has(source),
});

const runtimeCity = structuredClone(city);
if (city.cityPack) {
    const packSource = resolve(root, 'city-packs', cityId);
    if (!existsSync(packSource)) throw new Error(`Missing city pack directory: city-packs/${cityId}`);
    cpSync(packSource, resolve(output, 'city-pack'), { recursive: true });
    runtimeCity.cityPack = Object.fromEntries(Object.entries(city.cityPack).map(([phase, scripts]) => [
        phase,
        scripts.map(script => `city-pack/${script}`),
    ]));
}
writeFileSync(
    resolve(output, 'city-config.generated.js'),
    `// Generated by scripts/build.mjs from config/cities/${cityId}.json.\n`
        + `window.__TRANSIT_CITY_CONFIG__ = Object.freeze(${JSON.stringify(runtimeCity, null, 2)});\n`,
);

const vendor = resolve(output, 'vendor');
mkdirSync(vendor, { recursive: true });
const assets = [
    ['leaflet', 'dist/leaflet.css', 'leaflet/leaflet.css'],
    ['leaflet', 'dist/leaflet.js', 'leaflet/leaflet.js'],
    ['leaflet', 'dist/images', 'leaflet/images'],
    ['leaflet.heat', 'dist/leaflet-heat.js', 'leaflet-heat/leaflet-heat.js'],
    ['@turf/turf', 'turf.min.js', 'turf/turf.min.js'],
    ['html2canvas', 'dist/html2canvas.min.js', 'html2canvas/html2canvas.min.js'],
];
for (const [packageName, source, target] of assets) {
    const targetPath = resolve(vendor, target);
    mkdirSync(dirname(targetPath), { recursive: true });
    const packageRoot = dirname(require.resolve(`${packageName}/package.json`));
    cpSync(resolve(packageRoot, source), targetPath, { recursive: true });
}

const stationPackage = dirname(require.resolve('station3d/package.json'));
execFileSync(process.execPath, [
    resolve(stationPackage, 'bin/station3d-vendor.mjs'),
    '--force',
    resolve(vendor, 'station3d'),
], { cwd: root, stdio: 'inherit' });

console.log(`[build] city=${cityId} public=${output}`);
