import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { assertValidCityManifest } from './lib/city-manifest.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const sourceWeb = resolve(root, 'web');
const output = resolve(process.env.TRANSIT_DIST_DIR || resolve(root, 'dist'));
const require = createRequire(import.meta.url);
const cityId = String(process.env.TRANSIT_CITY || 'example').trim();
if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(cityId)) throw new Error('Invalid TRANSIT_CITY');

const cityPath = resolve(root, 'config/cities', `${cityId}.json`);
const city = JSON.parse(readFileSync(cityPath, 'utf8'));
assertValidCityManifest(city, cityId);

function optionalUrl(name, { allowPath = false } = {}) {
    const value = String(process.env[name] || '').trim();
    if (!value) return null;
    if (allowPath && /^\/[a-z0-9._~!$&'()*+,;=:@%/-]*\/?$/i.test(value)) return value;
    const url = new URL(value);
    if (!['http:', 'https:'].includes(url.protocol)) throw new Error(`${name} must be an HTTP(S) URL`);
    return url.href;
}

function normalizedBasePath(value) {
    if (!value) return null;
    if (!/^\/[a-z0-9._~!$&'()*+,;=:@%/-]*\/?$/i.test(value)) {
        throw new Error('TRANSIT_ASSET_BASE_PATH must be an absolute URL path');
    }
    return value.endsWith('/') ? value : `${value}/`;
}

function escapeAttribute(value) {
    return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;')
        .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function escapeText(value) {
    return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

const deployment = Object.freeze({
    assetBasePath: normalizedBasePath(process.env.TRANSIT_ASSET_BASE_PATH),
    publicUrl: optionalUrl('TRANSIT_PUBLIC_URL'),
    apiBaseUrl: optionalUrl('TRANSIT_API_BASE_URL', { allowPath: true }),
    valhallaIsochroneUrl: optionalUrl('TRANSIT_VALHALLA_ISOCHRONE_URL', { allowPath: true }),
    externalExplorerBaseUrl: optionalUrl('TRANSIT_EXTERNAL_EXPLORER_URL', { allowPath: true }),
});

rmSync(output, { recursive: true, force: true });
mkdirSync(output, { recursive: true });
const excludedSourcePaths = new Set([
    resolve(sourceWeb, 'vendor'),
    resolve(sourceWeb, 'city-config.generated.js'),
]);
cpSync(sourceWeb, output, {
    recursive: true,
    filter: source => !excludedSourcePaths.has(source),
});

const runtimeCity = structuredClone(city);
if (city.cityPack) {
    const packSource = resolve(root, 'city-packs', cityId);
    if (!existsSync(packSource)) throw new Error(`Missing city pack directory: city-packs/${cityId}`);
    cpSync(packSource, resolve(output, 'city-pack'), { recursive: true });
    runtimeCity.cityPack = Object.fromEntries(Object.entries(city.cityPack).map(([phase, scripts]) => [
        phase,
        phase === 'publicAssets' ? scripts : scripts.map(script => `city-pack/${script}`),
    ]));
    for (const asset of city.cityPack.publicAssets || []) {
        const source = resolve(packSource, asset.source);
        const target = resolve(output, asset.target);
        if (!source.startsWith(`${packSource}/`) || !target.startsWith(`${output}/`)) {
            throw new Error(`Unsafe public asset mapping: ${asset.source} -> ${asset.target}`);
        }
        if (!existsSync(source) || !statSync(source).isFile()) {
            throw new Error(`Missing city-pack public asset: ${asset.source}`);
        }
        if (existsSync(target)) {
            throw new Error(`City-pack public asset collides with core output: ${asset.target}`);
        }
        mkdirSync(dirname(target), { recursive: true });
        cpSync(source, target, { recursive: true });
    }
}
writeFileSync(
    resolve(output, 'city-config.generated.js'),
    `// Generated by scripts/build.mjs from config/cities/${cityId}.json.\n`
        + `window.__TRANSIT_CITY_CONFIG__ = Object.freeze(${JSON.stringify(runtimeCity, null, 2)});\n`,
);
writeFileSync(
    resolve(output, 'deployment-config.generated.js'),
    '// Generated by scripts/build.mjs from TRANSIT_* deployment settings.\n'
        + `window.__TRANSIT_APP_CONFIG__ = Object.freeze(${JSON.stringify({
            apiBaseUrl: deployment.apiBaseUrl,
            valhallaIsochroneUrl: deployment.valhallaIsochroneUrl,
            externalExplorerBaseUrl: deployment.externalExplorerBaseUrl,
        }, null, 2)});\n`,
);

function absoluteAssetUrl(value) {
    if (!value) return null;
    try { return new URL(value).href; } catch (_error) { /* relative */ }
    if (!deployment.publicUrl) return value;
    return new URL(value, deployment.publicUrl).href;
}

function replaceMeta(html, selector, content) {
    if (!content) return html;
    const escaped = escapeAttribute(content);
    const pattern = new RegExp(`(<meta\\s+${selector}\\s+content=")[^"]*(")`, 'i');
    return html.replace(pattern, `$1${escaped}$2`);
}

function brandHtml(filename) {
    const path = resolve(output, filename);
    if (!existsSync(path)) return;
    const branding = city.branding || {};
    let html = readFileSync(path, 'utf8');
    if (deployment.assetBasePath) {
        html = html.replace(/<head>/i,
            `<head>\n    <base href="${escapeAttribute(deployment.assetBasePath)}">`);
    }
    if (filename === 'transit.html') {
        const title = branding.plannerTitle || `${city.name} — Universal Transit Planner`;
        const description = branding.description;
        const socialImage = absoluteAssetUrl(branding.socialImage || 'transit-social-preview.svg');
        html = html.replace(/<title>[^<]*<\/title>/i, `<title>${escapeText(title)}</title>`);
        html = replaceMeta(html, 'name="description"', description);
        html = replaceMeta(html, 'property="og:site_name"', branding.siteName || 'Universal Transit Planner');
        html = replaceMeta(html, 'property="og:title"', title);
        html = replaceMeta(html, 'property="og:description"', description);
        html = replaceMeta(html, 'property="og:image"', socialImage);
        html = replaceMeta(html, 'name="twitter:title"', title);
        html = replaceMeta(html, 'name="twitter:description"', description);
        html = replaceMeta(html, 'name="twitter:image"', socialImage);
        if (deployment.publicUrl) {
            const publicUrl = escapeAttribute(deployment.publicUrl);
            html = html.replace('</title>', `</title>\n    <link rel="canonical" href="${publicUrl}">`);
            html = html.replace('</head>', `    <meta property="og:url" content="${publicUrl}">\n</head>`);
        }
    }
    writeFileSync(path, html);
}

brandHtml('transit.html');
brandHtml('leaderboard.html');

const vendor = resolve(output, 'vendor');
mkdirSync(vendor, { recursive: true });
const assets = [
    ['leaflet', 'dist/leaflet.css', 'leaflet/leaflet.css'],
    ['leaflet', 'dist/leaflet.js', 'leaflet/leaflet.js'],
    ['leaflet', 'dist/images', 'leaflet/images'],
    ['leaflet.heat', 'dist/leaflet-heat.js', 'leaflet-heat/leaflet-heat.js'],
    ['@turf/turf', 'turf.min.js', 'turf/turf.min.js'],
    ['html2canvas', 'dist/html2canvas.min.js', 'html2canvas/html2canvas.min.js'],
];
for (const [packageName, source, target] of assets) {
    const targetPath = resolve(vendor, target);
    mkdirSync(dirname(targetPath), { recursive: true });
    const packageRoot = dirname(require.resolve(`${packageName}/package.json`));
    cpSync(resolve(packageRoot, source), targetPath, { recursive: true });
}

const stationPackage = dirname(require.resolve('station3d/package.json'));
execFileSync(process.execPath, [
    resolve(stationPackage, 'bin/station3d-vendor.mjs'),
    '--force',
    resolve(vendor, 'station3d'),
], { cwd: root, stdio: 'inherit' });

console.log(`[build] city=${cityId} public=${output}`);
